google:
  oauth2:
    client:
      client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH2_SECRET_KEY}
      scope:
        - openid
        - profile
        - email
      redirect-uri: "http://localhost:8080/api/v1/account/social/google"