spring:
  config:
    import:
      - "application-jwt.yml"
      - "application-infra.yml"
      - "application-persistence.yml"
      - "application-google.yml"

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  port: 8078

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    enable:
      jvm: true
      gc: true
      memory: true
      processors: true
      files: true
      loggers: true
      tomcat: true

logging:
  level:
    org.springframework: INFO

client:
  redirect:
    url: "http://localhost:5173"