version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dayon
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dayon
      MYSQL_USER: dayon_user
      MYSQL_PASSWORD: dayon_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - dayon_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: redis_dayon
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dayon_network
    command: redis-server --appendonly yes --requirepass redis_password

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  dayon_network:
    driver: bridge