# @name 행정구역 데이터 저장
POST {{baseUrl}}/api/v1/districts/save-preprocessed?jsonFilePath=data/korean_administrative_districts_preprocessed.json
Content-Type: application/json
Accept: application/json

###

# @name 행정구역 데이터 전체 삭제
DELETE {{baseUrl}}/api/v1/districts/all
Content-Type: application/json

{
    "confirm": "DELETE_ALL"
}

###

# @name 강남역 10번 출구 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.497930&longitude=127.027490
Content-Type: application/json

###

# @name 강남역 11번 출구 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.498230&longitude=127.028140
Content-Type: application/json

###

# @name 서울시청 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.566535&longitude=126.978026

###

# @name 부산역 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=35.115619&longitude=129.041748

###

# @name 광화문 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.572956&longitude=126.976849

###

# @name 여의도 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.521507&longitude=126.924495

###

# @name 잠실역 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.513294&longitude=127.100108

###