# @name 행정구역 데이터 저장
POST {{baseUrl}}/api/v1/districts/save-preprocessed?jsonFilePath=data/korean_administrative_districts_preprocessed.json
Content-Type: application/json
Accept: application/json

###

# @name 행정구역 데이터 전체 삭제
DELETE {{baseUrl}}/api/v1/districts/all
Content-Type: application/json

{
    "confirm": "DELETE_ALL"
}

###

# @name 강남역 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.4979&longitude=127.0276
Content-Type: application/json

###

# @name 서울시청 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=37.5665&longitude=126.9780

###

# @name 부산역 좌표
GET {{baseUrl}}/api/v1/districts/search?latitude=35.1156&longitude=129.0417