spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dayon?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8mb4
    username: root
    password: rootpassword

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE