spring:
  config:
    import:
      - "application-persistence.yml"

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    enable:
      jvm: true
      gc: true
      memory: true
      processors: true
      files: true
      loggers: true
      tomcat: true

logging:
  level:
    org.springframework: INFO