spring:
  data:
    redis:
        host: localhost
        port: 6379
        repositories:
          enabled: false

logging:
  level:
    com.day.on: DEBUG
    org.springframework.data.redis: DEBUG
